services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprint_api_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: airport-db-aws.cb0gy0o209ik.us-east-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: "!two3fourfive"
