services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprint_api_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: 1two3Four5s!x78
