services:
  db:
    image: mysql:8.4
    container_name: sprint_api_db
    environment:
      MYSQL_ROOT_PASSWORD: 1two3Four5s!x78
      MYSQL_DATABASE: airport_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: App-pass1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u root -p1two3Four5s!x78 -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprint_api_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASS: App-pass1
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: